//USER STUFF
export const SET_USER = 'SET_USER';
export const SET_HANDLE_CHECK = 'SET_HANDLE_CHECK';
export const HANDLE_CHECKED = 'HANDLE_CHECKED';
export const SET_PROFILE_PICTURE = 'SET_PROFILE_PICTURE';
export const SET_LOGGED_IN_CHECK = 'SET_LOGGED_IN_CHECK';
export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
export const RESET_CURRENT_PROFILE = 'RESET_CURRENT_PROFILE';
export const LOGOUT = 'LOGOUT';
export const SET_USER_SEARCH_RESULT = 'SET_USER_SEARCH_RESULT';
export const SET_CREATED = 'SET_CREATED';

//DOG STUFF
export const SET_DOGS = 'SET_DOGS';
export const SET_CURRENT_DOG = 'SET_CURRENT_DOG';
export const SET_DOGS_SEARCH_RESULT = 'SET_DOGS_SEARCH_RESULT';
export const SET_DOGS_FROM_FEED = 'SET_DOGS_FROM_FEED';
export const SET_CURRENT_USER_DOGS = 'SET_CURRENT_USER_DOGS';
export const SET_IS_FROM_FEED = 'SET_IS_FROM_FEED';

//ANIMATION STUFF
export const SET_ANIMATION_START = 'SET_ANIMATION_START';
export const SET_ANIMATION_STOP = 'SET_ANIMATION_STOP';
